//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniConn_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMUNITY_MEMBERSHIP
    {
        public string student_id { get; set; }
        public string community_name { get; set; }
        public System.DateTime join_date { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual COMMUNITY COMMUNITY { get; set; }
        public virtual STUDENTS STUDENTS { get; set; }
    }
}
