//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniConn_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMUNITY_ROLE_ASSIGNMENT
    {
        public string student_id { get; set; }
        public string community_name { get; set; }
        public string role_title { get; set; }
        public string assigned_by { get; set; }
        public System.DateTime assigned_date { get; set; }
    
        public virtual STUDENTS STUDENTS { get; set; }
        public virtual STUDENTS STUDENTS1 { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
