//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniConn_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTS()
        {
            this.POST = new HashSet<POST>();
        }
    
        public int event_id { get; set; }
        public string event_name { get; set; }
        public string description { get; set; }
        public System.DateTime event_date { get; set; }
        public string location { get; set; }
        public string community_name { get; set; }
        public string creator_student_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public Nullable<bool> is_archived { get; set; }
    
        public virtual COMMUNITY COMMUNITY { get; set; }
        public virtual STUDENTS STUDENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST> POST { get; set; }
    }
}
