//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniConn_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POLL()
        {
            this.POLL_OPTION = new HashSet<POLL_OPTION>();
            this.VOTE = new HashSet<VOTE>();
        }
    
        public int poll_id { get; set; }
        public string poll_title { get; set; }
        public string poll_creator_student_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public Nullable<int> post_id { get; set; }
    
        public virtual STUDENTS STUDENTS { get; set; }
        public virtual POST POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POLL_OPTION> POLL_OPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOTE> VOTE { get; set; }
    }
}
