//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniConn_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POST()
        {
            this.POLL = new HashSet<POLL>();
        }
    
        public int post_id { get; set; }
        public string community_name { get; set; }
        public string creator_student_id { get; set; }
        public System.DateTime creation_date { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string image_url { get; set; }
        public Nullable<int> event_reference_id { get; set; }
    
        public virtual COMMUNITY COMMUNITY { get; set; }
        public virtual EVENTS EVENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POLL> POLL { get; set; }
        public virtual STUDENTS STUDENTS { get; set; }
    }
}
