//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniConn_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLE()
        {
            this.COMMUNITY_ROLE_ASSIGNMENT = new HashSet<COMMUNITY_ROLE_ASSIGNMENT>();
        }
    
        public string community_name { get; set; }
        public string role_title { get; set; }
        public string role_description { get; set; }
        public Nullable<bool> is_allowed_to_vote { get; set; }
        public Nullable<bool> can_remove_add_members { get; set; }
        public Nullable<bool> can_create_events { get; set; }
        public Nullable<bool> can_participate_in_polls { get; set; }
    
        public virtual COMMUNITY COMMUNITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMUNITY_ROLE_ASSIGNMENT> COMMUNITY_ROLE_ASSIGNMENT { get; set; }
    }
}
