//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniConn_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENTS()
        {
            this.COMMUNITY_MEMBERSHIP = new HashSet<COMMUNITY_MEMBERSHIP>();
            this.COMMUNITY_ROLE_ASSIGNMENT = new HashSet<COMMUNITY_ROLE_ASSIGNMENT>();
            this.COMMUNITY_ROLE_ASSIGNMENT1 = new HashSet<COMMUNITY_ROLE_ASSIGNMENT>();
            this.EVENTS = new HashSet<EVENTS>();
            this.POLL = new HashSet<POLL>();
            this.POST = new HashSet<POST>();
            this.VOTE = new HashSet<VOTE>();
        }
    
        public string student_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string institutional_email { get; set; }
        public System.DateTime registration_date { get; set; }
        public string status { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMUNITY_MEMBERSHIP> COMMUNITY_MEMBERSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMUNITY_ROLE_ASSIGNMENT> COMMUNITY_ROLE_ASSIGNMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMUNITY_ROLE_ASSIGNMENT> COMMUNITY_ROLE_ASSIGNMENT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTS> EVENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POLL> POLL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST> POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOTE> VOTE { get; set; }
    }
}
