//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniConn_CS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniConnDBEntities : DbContext
    {
        public UniConnDBEntities()
            : base("name=UniConnDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMMUNITY> COMMUNITY { get; set; }
        public virtual DbSet<COMMUNITY_MEMBERSHIP> COMMUNITY_MEMBERSHIP { get; set; }
        public virtual DbSet<COMMUNITY_ROLE_ASSIGNMENT> COMMUNITY_ROLE_ASSIGNMENT { get; set; }
        public virtual DbSet<EVENTS> EVENTS { get; set; }
        public virtual DbSet<POLL> POLL { get; set; }
        public virtual DbSet<POLL_OPTION> POLL_OPTION { get; set; }
        public virtual DbSet<POST> POST { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<STUDENTS> STUDENTS { get; set; }
        public virtual DbSet<VOTE> VOTE { get; set; }
    }
}
