//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniConn_CS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOTE
    {
        public int poll_id { get; set; }
        public string student_id { get; set; }
        public int poll_option_id { get; set; }
        public System.DateTime vote_date { get; set; }
    
        public virtual POLL POLL { get; set; }
        public virtual POLL_OPTION POLL_OPTION { get; set; }
        public virtual STUDENTS STUDENTS { get; set; }
    }
}
